[INFO    ] 2018-10-30T15:39:20.385967631Z: Running Test linuxkit.kernel.kmod_4.14.x in /tmp/with_clone174b5482/test/cases/020_kernel/012_kmod_4.14.x
[INFO    ] 2018-10-30T15:39:20.386282487Z: Running command: [/bin/sh -x /tmp/with_clone174b5482/test/cases/020_kernel/012_kmod_4.14.x/test.sh]
[STDERR  ] 2018-10-30T15:39:20.387310711Z: + set -e
[STDERR  ] 2018-10-30T15:39:20.387563976Z: + . /tmp/with_clone174b5482/test/cases/_lib/lib.sh
[STDERR  ] 2018-10-30T15:39:20.387600319Z: + [ -f src/github.com/linuxkit/rtf/lib/lib.sh ]
[STDERR  ] 2018-10-30T15:39:20.387626864Z: + LINUXKIT_TMPDIR=/tmp/with_clone174b5482/test/cases/_tmp
[STDERR  ] 2018-10-30T15:39:20.387687285Z: + [ -f /tmp/with_clone174b5482/test/cases/_tmp/env.sh ]
[STDERR  ] 2018-10-30T15:39:20.387743074Z: + . /tmp/with_clone174b5482/test/cases/_tmp/env.sh
[STDERR  ] 2018-10-30T15:39:20.387771311Z: + export LINUXKIT_EXAMPLES_DIR=/tmp/with_clone174b5482/test/cases/../../examples
[STDERR  ] 2018-10-30T15:39:20.387812519Z: + RT_CANCEL=253
[STDERR  ] 2018-10-30T15:39:20.387840626Z: + NAME=kmod
[STDERR  ] 2018-10-30T15:39:20.387866150Z: + IMAGE_NAME=kmod-test
[STDERR  ] 2018-10-30T15:39:20.387894380Z: + trap clean_up EXIT
[STDERR  ] 2018-10-30T15:39:20.387924523Z: + docker pull linuxkit/kernel:4.14.78
[STDERR  ] 2018-10-30T15:39:21.336466215Z: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
[STDERR  ] 2018-10-30T15:39:21.338077783Z: + clean_up
[STDERR  ] 2018-10-30T15:39:21.338156423Z: + docker rmi kmod-test
[STDERR  ] 2018-10-30T15:39:21.358532809Z: Error response from daemon: No such image: kmod-test:latest
[STDERR  ] 2018-10-30T15:39:21.359882515Z: + true
[STDERR  ] 2018-10-30T15:39:21.360042814Z: + rm -rf kmod-*
[FAIL    ] linuxkit.kernel.kmod_4.14.x 0.97s
